version: 2.1
orbs:
  python: circleci/python@2

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      - run:
          name: Create Deployment Directory
          command: |
            DEPLOY_DIR=DEPLOY-$(date +%Y-%m-%d)
            mkdir -p $DEPLOY_DIR

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            DEPLOY_DIR=DEPLOY-$(date +%Y-%m-%d)
            cd $DEPLOY_DIR
            python3 -m venv env  # Create a virtual environment
            . env/bin/activate     # Activate the virtual environment
            pip install poetry      # Install Poetry
            poetry install          # Install dependencies defined in pyproject.toml

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Deploy to S3
          command: |
            DEPLOY_DIR=DEPLOY-$(date +%Y-%m-%d)
            aws s3 cp $DEPLOY_DIR s3://devops-amanuensis-deploy/$DEPLOY_DIR --recursive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

