version: 2.1
orbs:
  python: circleci/python@2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install poetry
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install poetry
      - run:
          name: install dependencies
          command: |
            . env/bin/activate
            poetry install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


