version: 2.1
orbs:
  python: circleci/python@2
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/amanuensis
    steps:
      - checkout
      - run:
          name: install deps
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build


