version: 2.1
orbs:
  python: circleci/python@2

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout

      - run:
          name: Create Deployment Directory
          command: |
            DEPLOY_DIR="DEPLOY-$(date +%Y-%m-%d)"
            rm -rf "$DEPLOY_DIR"
            mkdir -p "$DEPLOY_DIR"
      
      - run:
          name: Copy Repository to Deployment Directory
          command: |
            DEPLOY_DIR="DEPLOY-$(date +%Y-%m-%d)"
            cp -r ./amanuensis/* "$DEPLOY_DIR/"

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            DEPLOY_DIR="DEPLOY-$(date +%Y-%m-%d)"
            cd "$DEPLOY_DIR"
            rm -rf env
            python3 -m venv env  # Create a virtual environment
            . env/bin/activate    # Activate the virtual environment 
            pip install -U pip    # Update pip to the latest version for compatibility
            curl -sSL https://install.python-poetry.org | python3 -  # Install the latest Poetry version
            export PATH="$HOME/.local/bin:$PATH"  # Ensure Poetry is in PATH
            poetry lock
            poetry install        # Install dependencies defined in pyproject.toml

      - run:
          name: Test project
          command: |
            DEPLOY_DIR="DEPLOY-$(date +%Y-%m-%d)"
            cd "$DEPLOY_DIR"
            . env/bin/activate
            pytest tests_project/test_overall_project_state.py
    
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Deploy to S3
          command: |
            DEPLOY_DIR="DEPLOY-$(date +%Y-%m-%d)"
            aws s3 cp "$DEPLOY_DIR" s3://devops-amanuensis-deploy/"$DEPLOY_DIR" --recursive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master
