version: 2.1
orbs:
  python: circleci/python@2

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.9
    environment:
      DEPLOY_DIR: "DEPLOY-$(date +%Y-%m-%d)"   # Define DEPLOY_DIR once here
    steps:
      - checkout

      - run:
          name: Create Deployment Directory
          command: |
          
            mkdir -p "$DEPLOY_DIR"
      
      - run:
          name: Copy Repository to Deployment Directory
          command: |
            cp -r ./amanuensis/* "$DEPLOY_DIR/"
      - run:
          name: Upgrade Pip
          command: |
            python -m pip install --upgrade pip

      - run:
          name: Upgrade Poetry
          command: |
            pip install --upgrade poetry

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            cd "$DEPLOY_DIR"
            python3 -m venv env  # Create a virtual environment
            . env/bin/activate     # Activate the virtual environment
            poetry install          # Install dependencies defined in pyproject.toml
    
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - run:
          name: Deploy to S3
          command: |
            aws s3 cp "$DEPLOY_DIR" s3://devops-amanuensis-deploy/"$DEPLOY_DIR" --recursive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master
